Elmohamady/Models/Item.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace Elmohamady.Models
{
    public class Item
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        [Range(10, 1000,
        ErrorMessage = "Value for {0} must be between {1} and {2}.")]
        public decimal Price { get; set; }
        public DateTime idCreatedDate { get; set; } = DateTime.Now;

        [Required]
        [DisplayName("Category")]
        [ForeignKey("Category")]
        public int CategoryId { get; set; }
        public string? imagePath { get; set; }
        [NotMapped]
        public IFormFile clientFile { get; set; }

        public Category? Category  { get; set; }




    }
}

Elmohamady/Controllers/ItemsController.cs
using Microsoft.AspNetCore.Mvc;
using Elmohamady.Data;
using Elmohamady.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;
using Microsoft.AspNetCore.Authorization;

namespace Elmohamady.Controllers
{
    [Authorize]

    public class ItemsController : Controller
        
    {
        public ItemsController(AppDbContext db ,IHostingEnvironment host)
        {
            _db = db;
            _host = host;

        }
        private readonly IHostingEnvironment _host;

        private readonly AppDbContext _db;
        public IActionResult Index()
        {
            IEnumerable<Item> itemlist = _db.items.Include(n => n.Category).ToList();
            return View(itemlist);
        }
        //get
        public IActionResult New()
        {
            createSelectList();
            return View();
        }
        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult New(Item item)
        {
            if (ModelState.IsValid)
            {
                /* image*/
                string fileName = Guid.NewGuid().ToString();
                if (item.clientFile != null)
                {
                    string myUpload = Path.Combine(_host.WebRootPath, "images");
                    // fileName = item.clientFile.FileName;
                    fileName += Path.GetExtension(item.clientFile.FileName);
                    string fullPath = Path.Combine(myUpload, fileName);
                    item.clientFile.CopyTo(new FileStream(fullPath, FileMode.Create));
                    item.imagePath = fileName;

                    
                }
                /* endimage*/

                _db.items.Add(item);
                _db.SaveChanges();
                TempData["successData"] = "Item has been added successfully";
                return RedirectToAction("Index");
            }
            else
            {
                return View(item);
            }
        }

        public void createSelectList(int selectId = 1)
        {
            //List<Category> categories = new List<Category> {
            //  new Category() {Id = 1, Name = "Select Category"},
            //  new Category() {Id = 2, Name = "Computers"},
            //  new Category() {Id = 3, Name = "Mobiles"},
            //  new Category() {Id = 4, Name = "Electric machines"},
            //};
            List<Category> categories = _db.Categories.ToList();
            SelectList listItems = new SelectList(categories, "Id", "Name", selectId);
            ViewBag.CategoryList = listItems;
        }
        //get
        public IActionResult Edit(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var item = _db.items.Find(Id);
            if (item == null)
            {
                return NotFound();
            }
            
            createSelectList(item.CategoryId);
            return View(item);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Item item)
        {
            if (item.Name == "100")
            {
                ModelState.AddModelError("Name", "Name can't equal 100");
            }
            if (ModelState.IsValid)
            {


                /* image*/
                string fileName = Guid.NewGuid().ToString();
                if (item.clientFile != null)
                {
                    string myUpload = Path.Combine(_host.WebRootPath, "images");
                    //fileName = item.clientFile.FileName;
                    fileName += Path.GetExtension(item.clientFile.FileName);
                    string fullPath = Path.Combine(myUpload, fileName);
                    item.clientFile.CopyTo(new FileStream(fullPath, FileMode.Create));
                    item.imagePath = fileName;

                }
                /* endimage*/

                _db.items.Update(item);
                _db.SaveChanges();
                TempData["successData"] = "Item has been updated successfully";
                return RedirectToAction("Index");
            }
            else
            {
                return View(item);
            }
        }

        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Deleteitem(int?id)
        {
            var item = _db.items.Find(id);
            if (item == null)
            {
                return NotFound();
                
            }

                _db.items.Remove(item);
                _db.SaveChanges();
                return RedirectToAction("Index");    

        }

        //GET
        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var item = _db.items.Find(Id);
            if (item == null)
            {
                return NotFound();
            }
            createSelectList(item.CategoryId);
            return View(item);
        }


    }
}

Elmohamady/Views/Items/Delete.cshtml
@model Item
@{
    ViewData["Title"] = "Delete";
}
<form method="post" asp-action="Deleteitem">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div row pb-2>
            <h2 class="text-primary">Delete Item</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
        </div>
         <div class="mb-3">
            <label asp-for="Price"></label>
            <input asp-for="Price" class="form-control" />
        </div>
        <div>
            <label asp-for="CategoryId"></label>
            <select asp-for="CategoryId" class="form-control" disabled asp-items="@ViewBag.CategoryList">
            </select>
        </div>
        <br />
        <hr />
        <button type="submit" class="btn btn-primary" style="width:150px">Delete</button>
        <a asp-action="Index" asp-controller="Items" class="btn btn-secondary" style="width:150px">
            back to items
        </a>

    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    @* <script>
        var loadFile = function (event) {
            var reader = new FileReader();
            reader.onload = function () {
                var myImg = document.getElementById('myImg');
                myImg.src = reader.result;
            }
            reader.readAsDataURL(event.target.files[0]);
        }
    </script> *@
}

Elmohamady/Views/Items/Edit.cshtml
@model Item
@{
    ViewData["Title"] = "Edit";
}
<form method="post" enctype="multipart/form-data">
    <div class="border p-3 mt-4">
        <div row pb-2>
            <h2 class="text-primary">Edit Item</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
         <div class="mb-3">
            <label asp-for="Price"></label>
            <input asp-for="Price" class="form-control" />
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="CategoryId"></label>
            <select asp-for="CategoryId" class="form-control"  asp-items="@ViewBag.CategoryList">
            </select>
        </div>
        <div>
            <input type="file" asp-for="clientFile" onchange="loadFile(event)" />
            <img id="myImg" height="200px" src="~/images/@Model.imagePath" />
@*            // <img src="~/images/@item.imagePath" style="width:48px" class="img-thumbnail" />
 *@
        </div>

         <br /> 
        <hr />
        <button type="submit" class="btn btn-primary" style="width:150px">Save</button>
        <a asp-action="Index" asp-controller="Items" class="btn btn-secondary" style="width:150px">
            back to items
        </a>

    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    @* <script>
        var loadFile = function (event) {
            var reader = new FileReader();
            reader.onload = function () {
                var myImg = document.getElementById('myImg');
                myImg.src = reader.result;
            }
            reader.readAsDataURL(event.target.files[0]);
        }
    </script> *@
}

Elmohamady/Views/Items/Index.cshtml
@model IEnumerable<Item>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3 ">
<partial name="_Notifications" />
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary text-end ">Items View</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Items" asp-action="New" class="btn btn-primary">
                <i class="bi bi-plus"></i> &nbsp; Add New Item
            </a>
        </div>
    </div>


    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">
                    Item Name
                </th>
                <th scope="col">
                    Item Price
                </th>
                <th scope="col">
                    Item Category
                </th>
                <th scope="col">
                    Item Images
                </th>
                
                 
                  <th scope="col">
                </th> 
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="table-primary">
                    <td scope="row" width="30%">
                        @item.Name
                    </td>
                    <td width="20%">
                        @item.Price
                    </td>
                    <td width="20%">
                        @item.Category.Name
                    </td>
                    <td width="20%">
                        <img src="~/images/@item.imagePath" style="width:48px" class="img-thumbnail" />
                    </td>


                    <td class="text-end">
                        <a asp-controller="Items" asp-action="Edit" asp-route-Id="@item.Id" class="btn btn-sm btn-success">
                                 <i class="bi bi-pencil"></i>
                           </a>
                        <a asp-controller="Items" asp-action="Delete" asp-route-Id="@item.Id" class="btn btn-sm btn-danger">
                                  <i class="bi bi-trash3"></i>
                           </a>
                      </td>
                    
                </tr>
            }
        </tbody>
    </table>
</div>

Elmohamady/Views/Items/New.cshtml
@model Item
@{
    ViewData["Title"] = "New";
}

<form method="post" enctype="multipart/form-data">
    <div class="border p-3 mt-4">
        <div row pb-2>
            <h2 class="text-primary">Add New</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
         <div class="mb-3">
            <label asp-for="Price"></label>
            <input asp-for="Price" class="form-control" />
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="CategoryId"></label>
            <select asp-for="CategoryId" class="form-control" asp-items="@ViewBag.CategoryList">
            </select>
            <span asp-validation-for="CategoryId" class="text-danger"></span>
        </div>
        <div>
            <input type="file" asp-for="clientFile" onchange="loadFile(event)" />
            <img id="myImg" height="200px" />
        </div>
        <div>
            <input type="file" asp-for="clientFile" onchange="loadFile(event)" />
            <img id="myImg" height="200px" />
        </div>
        <br />
        <hr />
        <button type="submit" class="btn btn-primary" style="width:150px">Save</button>
        <a asp-action="Index" asp-controller="Items" class="btn btn-secondary" style="width:150px">
            back to items
        </a>

    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
 
    <script>
        var loadFile = function (event) {
            var reader = new FileReader();
            reader.onload = function () {
                var myImg = document.getElementById("myImg");
                myImg.src = reader.result;
            }
            reader.readAsDataURL(event.target.files[0]);
        }
    </script>
}